export type Role = 'SUPERADMIN' | 'ADMIN' | 'MANAGER' | 'USER' | 'READONLY'

export type Permission =
  | 'VIEW_CONTACTS' | 'CREATE_CONTACTS' | 'EDIT_CONTACTS' | 'ARCHIVE_CONTACTS' | 'EXPORT_CONTACTS'
  | 'VIEW_SENSITIVE_TAGS' | 'MANAGE_TAGS'
  | 'VIEW_SUPPORT_LEVEL' | 'EDIT_SUPPORT_LEVEL'
  | 'MANAGE_TASKS'
  | 'MANAGE_MAILS'
  | 'MANAGE_QE'
  | 'VIEW_DOCUMENTS' | 'UPLOAD_DOCUMENTS' | 'DOWNLOAD_DOCUMENTS' | 'MANAGE_DOCUMENTS'
  | 'VIEW_PLANNING' | 'MANAGE_PLANNING' | 'EDIT_QUOTAS'
  | 'MANAGE_USERS' | 'MANAGE_ROLES'
  | 'MANAGE_SETTINGS' | 'MANAGE_API'
  | 'VIEW_AUDIT_LOG' | 'MANAGE_BACKUPS' | 'MAINTENANCE_ACCESS'

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPERADMIN: [
    'VIEW_CONTACTS', 'CREATE_CONTACTS', 'EDIT_CONTACTS', 'ARCHIVE_CONTACTS', 'EXPORT_CONTACTS',
    'VIEW_SENSITIVE_TAGS', 'MANAGE_TAGS',
    'VIEW_SUPPORT_LEVEL', 'EDIT_SUPPORT_LEVEL',
    'MANAGE_TASKS', 'MANAGE_MAILS', 'MANAGE_QE',
    'VIEW_DOCUMENTS', 'UPLOAD_DOCUMENTS', 'DOWNLOAD_DOCUMENTS', 'MANAGE_DOCUMENTS',
    'VIEW_PLANNING', 'MANAGE_PLANNING', 'EDIT_QUOTAS',
    'MANAGE_USERS', 'MANAGE_ROLES',
    'MANAGE_SETTINGS', 'MANAGE_API',
    'VIEW_AUDIT_LOG', 'MANAGE_BACKUPS', 'MAINTENANCE_ACCESS'
  ],
  ADMIN: [
    'VIEW_CONTACTS', 'CREATE_CONTACTS', 'EDIT_CONTACTS', 'ARCHIVE_CONTACTS', 'EXPORT_CONTACTS',
    'VIEW_SENSITIVE_TAGS', 'MANAGE_TAGS',
    'VIEW_SUPPORT_LEVEL', 'EDIT_SUPPORT_LEVEL',
    'MANAGE_TASKS', 'MANAGE_MAILS', 'MANAGE_QE',
    'VIEW_DOCUMENTS', 'UPLOAD_DOCUMENTS', 'DOWNLOAD_DOCUMENTS', 'MANAGE_DOCUMENTS',
    'VIEW_PLANNING', 'MANAGE_PLANNING', 'EDIT_QUOTAS',
    'MANAGE_USERS', // except superadmin
    'MANAGE_SETTINGS',
    'VIEW_AUDIT_LOG'
  ],
  MANAGER: [
    'VIEW_CONTACTS', 'CREATE_CONTACTS', 'EDIT_CONTACTS',
    'VIEW_SENSITIVE_TAGS',
    'MANAGE_TASKS', 'MANAGE_MAILS', 'MANAGE_QE',
    'VIEW_DOCUMENTS', 'UPLOAD_DOCUMENTS', 'DOWNLOAD_DOCUMENTS',
    'VIEW_PLANNING', 'MANAGE_PLANNING' // only for their team, logic in code
  ],
  USER: [
    'VIEW_CONTACTS', 'CREATE_CONTACTS', 'EDIT_CONTACTS',
    'MANAGE_TASKS', 'MANAGE_MAILS', 'MANAGE_QE',
    'VIEW_DOCUMENTS', 'UPLOAD_DOCUMENTS', 'DOWNLOAD_DOCUMENTS',
    'VIEW_PLANNING' // only their own planning
  ],
  READONLY: [
    'VIEW_CONTACTS', 'VIEW_DOCUMENTS', 'VIEW_PLANNING'
  ]
}

export function hasPermission(role: string | undefined | null, permission: Permission): boolean {
  if (!role) return false
  const r = role as Role
  return ROLE_PERMISSIONS[r]?.includes(permission) || false
}

export function requirePermission(role: string | undefined | null, permission: Permission) {
  if (!hasPermission(role, permission)) {
    throw new Error(`Accès refusé. Permission requise: ${permission}`)
  }
}
